name: Deploy via SSH (git pull)

on:
  push:
    branches:
      - main   # <-- remplace par ta branche si besoin

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Deploy on Infomaniak (SSH + git pull)
        uses: appleboy/ssh-action@v1.2.0
        continue-on-error: true
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
          port: ${{ secrets.SSH_PORT }}
          script_stop: true
          script: |
            set -e

            APP_DIR="${{ secrets.APP_DIR }}"
            BRANCH="main"  # <-- garde en phase avec 'on.push.branches'

            echo "➡️  CD ${APP_DIR}"
            cd "${APP_DIR}"

            # On force à renvoyer 0 même si git pull retourne une erreur
            git pull || true

            echo "✅ Déploiement terminé (même si warning ou erreur ignorée)"

      - name: Wait 5 seconds
        run: sleep 5

      - name: Restart
        uses: appleboy/ssh-action@v1.2.0
        continue-on-error: true
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
          port: ${{ secrets.SSH_PORT }}
          script_stop: true
          script: |
            set -e

            APP_DIR="${{ secrets.APP_DIR }}"
            BRANCH="main"  # <-- garde en phase avec 'on.push.branches'

            echo "➡️  CD ${APP_DIR}"
            cd "${APP_DIR}"

            # On ignore tout code d'erreur éventuel de pm2
            npx pm2 restart index || true

            echo "✅ Redémarrage terminé (erreurs ignorées)"
